### PR TITLE
use -e, and slightly nicer formatting

### PR DESCRIPTION
**Pull request by pheaver**
Hi, saw your post on reddit and that you had updated your code based on a suggestion. Someone had also suggested used "-e" so you didn't have to use "&&". I made these changes to your script and tested it, and it still worked :).

### CODE REVIEW

**Comment by trozler** [comment]
Hi, I actually found an error with the code. Try running it when not connected to the internet. 
It doesn't print the correct error message. 
I'm trying to figure out how to fix it,  but I'm not exactly sure.  
Help would be appriciated.
```
$ myip
 - , .
```

**Comment by trozler** [comment]
I reverted to the old code, not sure how to fix it with -e. Will keep looking.

**Comment by pheaver** [comment]
Ah, whoops, I see what you mean. I'm not sure why it behaves like that, but it looks like you can replace the curly braces (`{` and `}`) with parentheses (`(` and `)`), and then it will behave as expected.

**Comment by trozler** [comment]
Ah interesting so it works if forks a new process. 
Anyways, thanks a lot !

**Pull request merged**
